Makefile:

The top level Makefile file is split into 3 parts. The list of sub-projects to be compiled, copying of said files to chroot "binary", and the methods of sub-projects being compiled. To add new projects, add a script to download source, "cd" to it, and compile, to "scripts/" directory. The downloaded source will go into the "src" directory. If needed, add the --prefix to each added project. If that is not possible, add some way to move the compiled binary from the source directory to the out directory "root/"
